#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build RR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "format %y.%-m.$i or auto"
        required: false
        type: string
      prerelease:
        description: "pre release"
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        #with:
        #  lfs: 'true'

      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: RROrg/rr
          token: ${{ secrets.RRORG }}
          path: rr

      # Install dependencies
      - name: Install dependencies
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

          sudo apt update
          sudo apt install -y jq cpio gettext
          sudo snap install yq

      # calculates the version number and push
      - name: Calculate version
        run: |
          # Calculate version
          TAGDATE="$(date +'%Y%m%d%H%M')"
          VERSION=""

          if [ -n "${{ inputs.version }}" ]; then
            if [ "$(echo ${{ inputs.version }} | cut -d '.' -f 1,2)" = "$(date +'%y.%-m')" ]; then
              VERSION="${{ inputs.version }}"
            else
              LATEST_TAG="$(curl -skLH "Authorization: token ${{ secrets.RRORG }}" "https://api.github.com/repos/RROrg/rr/releases" | jq -r ".[0].tag_name" 2>/dev/null)"
              if [ -n "${LATEST_TAG}" -a "$(echo ${LATEST_TAG} | cut -d '.' -f 1,2)" = "$(date +'%y.%-m')" ]; then  # format %y.%-m.$i
                VERSION="$(echo ${LATEST_TAG} | awk -F '.' '{$3=$3+1}1' OFS='.')"
              else
                VERSION="$(date +'%y.%-m').0"
              fi
            fi
          else
            VERSION=""
          fi

          echo "TAGDATE: ${TAGDATE}"
          echo "VERSION: ${VERSION}"
          echo "TAGDATE=${TAGDATE}" >>$GITHUB_ENV
          echo "VERSION=${VERSION}" >>$GITHUB_ENV

          if [ -n "${VERSION}" ]; then
            cd rr

            # Modify Source File
            echo "${VERSION}" >VERSION
            echo "${VERSION}" >files/mnt/p1/RR_VERSION
            sed -i "s/^RR_VERSION=.*$/RR_VERSION=\"${VERSION}\"/" files/initrd/opt/rr/include/consts.sh

            git checkout main
            git pull
            status=$(git status -s | awk '{printf " %s", $2}')
            if [ -n "${status}" ]; then
              git add ${status}
              git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
              git push -f
            fi
          else
            cd rr

            sed -i "s/^RR_VERSION=.*$/RR_VERSION=\"${TAGDATE}\"/" files/initrd/opt/rr/include/consts.sh
          fi

      # Convert po2mo, Get exts
      - name: Convert po2mo, Get extractor, LKMs, addons and Modules
        run: |

          PRE="${{ inputs.prerelease }}"

          cd rr
          . scripts/func.sh "${{ secrets.RRORG }}"

          echo "Get extractor"
          getCKs "files/mnt/p3/cks" "${PRE}"
          getLKMs "files/mnt/p3/lkms" "${PRE}"
          getAddons "files/mnt/p3/addons" "${PRE}"
          getModules "files/mnt/p3/modules" "${PRE}"
          getBuildroot "files/mnt/p3" "${PRE}"
          getExtractor "files/mnt/p3/extractor"

          echo "Repack initrd"
          
          [ "${PRE}" = "true" ] && RELEASE="pre" || RELEASE=""
          sed -i "s/^RR_RELEASE=.*$/RR_RELEASE=\"${RELEASE}\"/" files/initrd/opt/rr/include/consts.sh

          convertpo2mo "files/initrd/opt/rr/lang"
          repackInitrd "files/mnt/p3/initrd-rr" "files/initrd"

          echo "OK"

      # Build incremental
      - name: Build image
        run: |
          cd rr
          . scripts/func.sh "${{ secrets.RRORG }}"

          echo "Create RR_1GB image"
          gzip -dc "files/initrd/opt/rr/grub.img.gz" >"rr_1GB.img"
          fdisk -l "rr_1GB.img"

          LOOPX=$(sudo losetup -f)
          sudo losetup -P "${LOOPX}" "rr_1GB.img"

          echo "Mounting image file"
          mkdir -p "/tmp/p1"
          mkdir -p "/tmp/p3"
          sudo mount ${LOOPX}p1 "/tmp/p1"
          sudo mount ${LOOPX}p3 "/tmp/p3"

          echo "Copying files"
          sudo cp -Rf "files/mnt/p1/"* "/tmp/p1"
          sudo cp -Rf "files/mnt/p3/"* "/tmp/p3"
          sync

          echo "Unmount image file"
          sudo umount "/tmp/p1"
          sudo umount "/tmp/p3"
          rmdir "/tmp/p1"
          rmdir "/tmp/p3"

          sudo losetup --detach ${LOOPX}

          echo "Create RR_4GB image" # $((1024 * 3 - 512))
          resizeImg "rr_1GB.img" "+2560M" "rr.img"

          # echo "Image Converter"
          # qemu-img convert -O vmdk rr.img rr-dyn.vmdk
          # qemu-img convert -O vmdk -o adapter_type=lsilogic rr.img -o subformat=monolithicFlat rr.vmdk

      # Zip image and generate checksum
      - name: Pack
        run: |
          cd rr
          TAGDATE="${{ env.TAGDATE }}"
          VERSION="${{ env.VERSION }}"
          VERSION="${VERSION:-"${TAGDATE}"}"

          zip -9 "rr_1GB-${VERSION}.img.zip" rr_1GB.img
          zip -9 "rr-${VERSION}.img.zip" rr.img
          # zip -9 "rr-${VERSION}.vmdk-dyn.zip" rr-dyn.vmdk
          # zip -9 "rr-${VERSION}.vmdk-flat.zip" rr.vmdk rr-flat.vmdk

          # update.zip
          sha256sum update-list.yml update-check.sh >sha256sum
          zip -9j "update-${VERSION}.zip" update-list.yml update-check.sh
          while read F; do
            if [ -d "${F}" ]; then
              FTGZ="$(basename "${F}").tgz"
              tar -zcf "${FTGZ}" -C "${F}" .
              sha256sum "${FTGZ}" >>sha256sum
              zip -9j "update-${VERSION}.zip" "${FTGZ}"
              rm -f "${FTGZ}"
            else
              (cd $(dirname "${F}") && sha256sum $(basename "${F}")) >>sha256sum
              zip -9j "update-${VERSION}.zip" "${F}"
            fi
          done < <(yq '.replace | explode(.) | to_entries | map([.key])[] | .[]' update-list.yml)
          zip -9j "update-${VERSION}.zip" sha256sum

          # updateall.zip
          rm -f sha256sum
          echo '  "files/mnt/p3/cks/": "/mnt/p3/cks/"' >>update-list.yml
          echo '  "files/mnt/p3/lkms/": "/mnt/p3/lkms/"' >>update-list.yml
          echo '  "files/mnt/p3/addons/": "/mnt/p3/addons/"' >>update-list.yml
          echo '  "files/mnt/p3/modules/": "/mnt/p3/modules/"' >>update-list.yml

          zip -9j "updateall-${VERSION}.zip" update-list.yml update-check.sh
          while read F; do
            if [ -d "${F}" ]; then
              FTGZ="$(basename "${F}").tgz"
              tar -zcf "${FTGZ}" -C "${F}" .
              sha256sum "${FTGZ}" >>sha256sum
              zip -9j "updateall-${VERSION}.zip" "${FTGZ}"
              rm -f "${FTGZ}"
            else
              (cd $(dirname "${F}") && sha256sum $(basename "${F}")) >>sha256sum
              zip -9j "updateall-${VERSION}.zip" "${F}"
            fi
          done < <(yq '.replace | explode(.) | to_entries | map([.key])[] | .[]' update-list.yml)
          zip -9j "updateall-${VERSION}.zip" sha256sum

      # Upload artifact
      - name: Upload to Artifacts
        if: success() && env.VERSION == ''
        uses: actions/upload-artifact@v4
        with:
          name: rr-${{ env.TAGDATE }}
          path: |
            rr/rr-*.zip
            rr/update*.zip
          retention-days: 5

      # Upload artifact
      - name: Upload to Artifacts
        if: success() && env.VERSION != ''
        uses: actions/upload-artifact@v4
        with:
          name: rr-${{ env.VERSION }}
          path: |
            rr/rr_*.zip
          retention-days: 5

      # Publish a release if is a tag
      - name: Release
        if: success() && env.VERSION != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          prerelease: ${{ inputs.prerelease }}
          artifacts: |
            rr/rr-*.zip
            rr/update*.zip
          body: |
            - Editing ...
          owner: RROrg
          repo: rr
          token: ${{ secrets.RRORG }}
